# Settings
- defaults:
    link:
      create: true
      relink: true
      force: true # Swap original file

# TODO: ?
- clean: ["~", "~/.config"]

  # Run shell commands
- shell:
    # Install submodules
    - [git submodule update --init --recursive, Installing submodules]

# Symlink files
- link:
    # Zsh
    ~/.zshrc: zsh/zshrc
    # Git
    ~/.gitconfig: git/gitconfig
    # ~/.gitignore_global: git/gitignore_global
    # Alacritty
    ~/alacritty.yml: alacritty/alacritty.yml
    # TMUX
    ~/.tmux.conf: tmux/tmux.conf
    # Neovim
    ~/.config/nvim: nvim
    # VS Code
    ~/Library/Application Support/Code/User/settings.json: vscode/settings.json
