# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the action will run. 
on: [push, pull_request]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Test 'make help'
      run: make help
    - name: Test 'make brew'
      run: make brew
    - name: Test 'make dotfiles'
      run: make dotfiles
    - name: Test 'make tools'
    - run: make tools
    - name: test 'make all'
      run: make all
